Fixed SearchVideos
Tyrrrz/YoutubeExplode pull request #439
Opened 2020-09-11 18:07 UTC by Unreal852

2020-09-11 19:11 UTC, Hexer10 requested changes

2020-09-11 19:11 UTC, Hexer10 commented on YoutubeExplode/YoutubeClient.cs
> +            httpClient.DefaultRequestHeaders.Add("x-youtube-client-version", "20200911");
These headers should be added only to the request that calls the search api, if you put them in the other requests they will fail; try to run the unit tests.

2020-09-11 20:27 UTC, Unreal852 commented
whoops didn't think about that, i fixed it. Altrought i still have issues with Closed Captions and Streams.

2020-09-11 21:49 UTC, Hexer10 commented
Well... Yeah that the video used in the unit tests is now private: https://www.youtube.com/watch?v=_QdPW8JrYzQ , if you want you can check my Dart version of this library and update the tests from there


https://github.com/Hexer10/youtube_explode_dart/blob/master/test/closed_caption_test.dart#L15-L41

2020-09-12 11:23 UTC, merged

2020-09-12 11:23 UTC, Tyrrrz commented
Thanks!